#!/usr/bin/env bash
#-*- coding: utf-8 -*-

repo_dir=$(git rev-parse --show-toplevel)
package_path=$repo_dir

product_name=OrzSwiftDoc
swift package                       \
    --disable-sandbox               \
    --package-path $package_path    \
    preview-documentation
    